services:
  next:
    build:
      context: .
      target: next
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
    volumes:
      - ".:/app"
    command: ["npm", "run", "dev"]
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    #    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    #    restart: always
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy