services:
  locallink-next:
    container_name: locallink-next
    build:
      context: .
      target: next
    environment:
      - NODE_ENV=development
    ports:
      - "80:80"
    volumes:
      - ".:/app"
    command: ["npm", "run", "dev"]
    depends_on:
      locallink-db:
        condition: service_healthy

  locallink-db:
    container_name: locallink-db
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  locallink-adminer:
    container_name: locallink-adminer
    image: adminer
    #    restart: always
    ports:
      - "8080:8080"
    depends_on:
      locallink-db:
        condition: service_healthy