services:
  locallink-next:
    container_name: locallink-next
    build:
      context: .
      target: next
    environment:
      - NODE_ENV=development
      - GOOGLE_ID=${GOOGLE_ID}
      - GOOGLE_SECRET=${GOOGLE_SECRET}
      - DATABASE_URL=postgres://postgres:password@locallink-db:5432/postgres
    env_file:
      - .env
      - .env.test
      - .env.local
    ports:
      - "3000:80"
    volumes:
      - ".:/app"
    command: ["npm", "run", "dev"]
    depends_on:
      locallink-db:
        condition: service_healthy

  locallink-db:
    container_name: locallink-db
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5