services:
  locallink-next-test:
    container_name: locallink-next-test
    build:
      context: .
      target: next
    ports:
      - "3030:80"
    volumes:
      - ".:/app"
    command: [ "npm", "run", "dev" ]
    depends_on:
      locallink-db-test:
        condition: service_healthy

  locallink-db-test:
    container_name: locallink-db-test
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5